const { Router } = require('express');
const router = Router();

const { historiaController } = require('../controller/index.controller');

router.get('/historiaPaciente/:id', historiaController.getHistoriaPaciente);
router.get('/historiaPacienteEnfermera/:id', historiaController.getHistoriaPacienteEnfermera);
router.get('/personaHistoriaPDF/:id', historiaController.getPersonaHistoriaPDF);
router.get('/personaHistoriaPDFCabecera/:id', historiaController.getPersonaHistoriaPDFCabecera);
router.get('/historiaPacienteAntecedentes/:id', historiaController.getHistoriaPacienteAntecedentes);
router.get('/diagnosticos/:id', historiaController.getDiagnosticos);
router.get('/medicamentos/:id', historiaController.getMedicamentos);
router.get('/estudios/:id', historiaController.getEstudios);
router.get('/frecuencia_viaAdministracion', historiaController.getFrecuencia_viaAdministracion);
router.get('/familiaRol', historiaController.getFamiliaRol);
router.get('/antecedentePatologico/:id', historiaController.getAntecedentePatologico);
router.get('/antecedenteMedicamento/:id', historiaController.getAntecedenteMedicamento);
router.get('/antecedenteHeredoFamiliar/:id', historiaController.getAntecedenteHeredoFamiliar);
router.get('/antecedenteQuirurgico/:id', historiaController.getAntecedenteQuirurgico);
router.get('/antecedenteNoPatologico/:id', historiaController.getAntecedenteNoPatologico);
router.get('/consultaBasica/:id', historiaController.getConsultaBasica);
router.get('/informacionadicional/:id', historiaController.getInformacionAdicional);
router.get('/consultaBasicaGinecologia/:id', historiaController.getConsultaBasicaGinecologia);
router.get('/consultaOftalomologia/:id', historiaController.getConsultaOftalomologia);
router.get('/consultaOftalomologiaDetalle/:id', historiaController.getConsultaOftalomologiaDetalle);
router.get('/enfermeria/:id', historiaController.getEnfermeria);
router.get('/habitaciones', historiaController.getHabitacion);
router.get('/camaPaciente/:id', historiaController.getCamaPaciente);
router.get('/diagnosticosInternacion/:id', historiaController.getDiagnosticosInternacion);
router.get('/hojaEvolcuion/:id', historiaController.getHojaEvolcuion);
router.get('/notasEnfermeria/:id', historiaController.getNotasEnfermeria);
router.get('/interconsulta/:id', historiaController.getInterconsulta);
router.get('/dietas', historiaController.getDietas);
router.get('/estudiosEmergencia/:id', historiaController.getEstudiosEmergencia);
router.get('/indicacionesView/:id', historiaController.getIndicacionesView);
router.get('/indicacionesViewExtras/:id', historiaController.getIndicacionesViewExtras);
router.get('/indicacionesEnfermeriaView/:id', historiaController.getIndicacionesEnfermeriaView);
router.get('/noMostrarEmergencia/:id', historiaController.getNoMostrarEmergencia);
router.get('/medicionAmulatorioEmergencia/:id', historiaController.getMedicionAmulatorioEmergencia);
router.get('/hojaNotasIngreso/:id', historiaController.getHojaNotasIngreso);
router.get('/ordenesHospitalizacion', historiaController.getOrdenesHospitalizacion);
router.get('/camasEmergencia', historiaController.getCamasEmergencia);
router.get('/medicionEmergencia/:id', historiaController.getMedicionEmergenciaEnfermeria);
router.get('/estudiosExamenesNew', historiaController.getEstudiosExamenesNew);

router.post('/updateDoctorTratante', historiaController.updateDoctorTratante);
router.post('/personaHistoria', historiaController.getPersonaHistoria);
router.post('/insertAntecedentePatologico', historiaController.insertAntecedentePatologico);
router.post('/removeAntecedentePatologico', historiaController.removeAntecedentePatologico);
router.post('/insertAntecedenteNoPatologico', historiaController.insertAntecedenteNoPatologico);
router.post('/removeAntecedenteNoPatologico', historiaController.removeAntecedenteNoPatologico);
router.post('/insertAntecedenteMedicamento', historiaController.insertAntecedenteMedicamento);
router.post('/removeAntecedenteMedicamento', historiaController.removeAntecedenteMedicamento);
router.post('/insertAntecedenteHeredoFamiliar', historiaController.insertAntecedenteHeredoFamiliar);
router.post('/removeAntecedenteHeredoFamiliar', historiaController.removeAntecedenteHeredoFamiliar);
router.post('/insertAntecedenteQuirurgico', historiaController.insertAntecedenteQuirurgico);
router.post('/removeAntecedenteQuirurgico', historiaController.removeAntecedenteQuirurgico);
router.post('/insertInformacionAdicional', historiaController.insertInformacionAdicional);
router.post('/updateInformacionAdicional', historiaController.updateInformacionAdicional);
router.post('/insertTriaje', historiaController.insertTriaje);
router.post('/turnoProgamadoListaFechaMedico', historiaController.getTurnoProgamadoListaFechaMedico);
router.post('/insertTriajeEmergencia', historiaController.insertTriajeEmergencia);
router.post('/insertEstudiosEmergencia', historiaController.insertEstudiosEmergencia);
router.post('/insertHojaEvolucion', historiaController.insertHojaEvolucion);
router.post('/insertInterconsulta', historiaController.insertInterconsulta);
router.post('/insertInterconsultaComentarios', historiaController.insertInterconsultaComentarios);
router.post('/insertNotasEnfermeria', historiaController.insertNotasEnfermeria);
router.post('/insertIndicaciones', historiaController.insertIndicaciones);
router.post('/insertIndicacionesEnfermeria', historiaController.insertIndicacionesEnfermeria);
router.post('/insertConsultaBasica', historiaController.insertConsultaBasica);
router.post('/insertAlta', historiaController.insertAlta);
router.post('/insertHojaNotaIngreso', historiaController.insertHojaNotaIngreso);
router.post('/insertConsultaBasicaAmbulatoria', historiaController.insertConsultaBasicaAmbulatoria);
router.post('/insertCamaHospitalizacion', historiaController.insertCamaHospitalizacion);
router.post('/insertBalance', historiaController.insertBalance);
router.post('/accessoSistemaMedico', historiaController.accessoSistemaMedico);
router.post('/cambiarUsuario', historiaController.cambiarUsuario);

module.exports = router;